### ISSUE TITLE
Provide a Docker image for linux/arm64

### ISSUE THREAD

**Issue by owenthereal** [emscripten-core/emscripten-ci#2] opened 2023-07-30 14:50 UTC
It would be nice that https://hub.docker.com/r/emscripten/emsdk/ can have a linux/arm64 image which makes running the image on  a m1/m2 mac faster.

**Comment by sbc100** [comment] 2023-07-30 18:00
I think this is a duplicate of https://github.com/emscripten-core/emsdk/issues/1211

**Closed as completed by sbc100** 2023-07-30 18:00 UTC
